### PR TITLE
Intellij-friendly code structure

### PR DESCRIPTION
**Pull request by wingsoverglades**
This program structure should be easier to work with, it's the one generated by Intellij and I converted the Java files to Kotlin.

### CODE REVIEW

**Comment by djlazz3** [comment]
do you want me to merge now or later?

**Comment by wingsoverglades** [comment]
I want you to clone that branch into your IDE and see if your IDE makes
sense of it, if you can build with no problems then we should merge, if
Android Studio complain and prefers the other format then keep them
separate for now.

**Comment by djlazz3** [comment]
yeah my android studio is asking me to convert to gradle

**Comment by wingsoverglades** [comment]
Intellij uses Ant, I think we can use the same exact repo with both Gradle
and Ant files, minor issue.

**Comment by djlazz3** [comment]
so how do you want me to deal with this because its not letting me compile/run?

**Comment by wingsoverglades** [comment]
Android Studio just tells you to configure Gradle? Doesn't give you any
steps to do that?

**Comment by djlazz3** [comment]
its giving me this as an error

> The SDK directory 'C:\Users\bpadr_000\Desktop\AppChallenge-Intellij\AppChallenge-Intellij\home\wingsoverglades\Development\Dependencies\android\android-sdk-linux' does not exist.

i wanted to know if you can understand it

**Comment by djlazz3** [comment]
i tried following the instructions that the ide gave me

**Pull request merged**
